// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyByqPsjdva3jCRMCX96FwaQNvnAZndkQX0',
    appId: '1:861261774181:web:5170eba10337cb3ff1358c',
    messagingSenderId: '861261774181',
    projectId: 'inboxiq--api',
    authDomain: 'inboxiq--api.firebaseapp.com',
    storageBucket: 'inboxiq--api.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3qHTVlyT8P98GPl6cmdR7Ob9QGuQa-QE',
    appId: '1:861261774181:android:56de935bbfd21ab7f1358c',
    messagingSenderId: '861261774181',
    projectId: 'inboxiq--api',
    storageBucket: 'inboxiq--api.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArpe7ruzCLTlHHtXkwGQ2XibkeMYioRYM',
    appId: '1:861261774181:ios:0a494e231da80e93f1358c',
    messagingSenderId: '861261774181',
    projectId: 'inboxiq--api',
    storageBucket: 'inboxiq--api.firebasestorage.app',
    androidClientId: '861261774181-f29dderckau7jehjirqdbgfkr3qdqgcl.apps.googleusercontent.com',
    iosClientId: '861261774181-biet2ln0n7ruo8nranfr00shfotfnaqm.apps.googleusercontent.com',
    iosBundleId: 'com.actionmail.actionmail',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyArpe7ruzCLTlHHtXkwGQ2XibkeMYioRYM',
    appId: '1:861261774181:ios:0a494e231da80e93f1358c',
    messagingSenderId: '861261774181',
    projectId: 'inboxiq--api',
    storageBucket: 'inboxiq--api.firebasestorage.app',
    androidClientId: '861261774181-f29dderckau7jehjirqdbgfkr3qdqgcl.apps.googleusercontent.com',
    iosClientId: '861261774181-biet2ln0n7ruo8nranfr00shfotfnaqm.apps.googleusercontent.com',
    iosBundleId: 'com.actionmail.actionmail',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyByqPsjdva3jCRMCX96FwaQNvnAZndkQX0',
    appId: '1:861261774181:web:9aea2c3c0a812d03f1358c',
    messagingSenderId: '861261774181',
    projectId: 'inboxiq--api',
    authDomain: 'inboxiq--api.firebaseapp.com',
    storageBucket: 'inboxiq--api.firebasestorage.app',
  );
}
